steps:
  # npm install, build, and test
  - id: 'npm install'
    name: 'node:12.10-alpine'
    args: ['npm', 'install']

  - id: 'npm run build'
    name: 'node:12.10-alpine'
    args: ['npm', 'run', 'build']

  - id: 'npm run test'
    name: 'node:12.10-alpine'
    args: ['npm', 'run', 'test']