steps:
  # npm install, build, and test
  - id: "npm install"
    name: "node:12.10-alpine"
    args: ["npm", "install"]

  - id: "npm run build"
    name: "node:12.10-alpine"
    args: ["npm", "run", "build"]

  - id: "npm run test"
    name: "node:12.10-alpine"
    args: ["npm", "run", "test"]

  # build docker container
  - id: "docker build"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/home", "."]

# tag image for search
tags: ["personal-website", "home"]
images:
  - gcr.io/$PROJECT_ID/home
